language: java

jdk: openjdk8

services:
   - docker

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
#   - mvn -f dockerExample/pom.xml clean verify -Pdocker
   - mvn -f docker-network/pom.xml clean verify