language: java

jdk: openjdk8

services:
   - docker

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f docker-repository-01/pom.xml clean verify -Pdocker